# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: qtADh/y50uEXskowCCf8jdS3yOlV0HW3PHlXV/R6KL+3sVxygsCwMfkhwUWULuFL

test:
  secret_key_base: 2d3fa4cd6244ffe06c65d14431f6eff0dfa11ef0c3cd30e79943ca470e87044c9ac5448fcd7fa7deedb9d76b0cd2590bc248c6eb4c4af3effd735dea9bd9608a

# Do not keep production secrets in the repository,
# instead read values from the environment.
acceptance:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
